#image: java:8
image: maven:latest

stages:
  - build
  - test

build:
  stage: build
  script: mvn package
  artifacts:
    paths:
      - target/java-project-0.0.1-SNAPSHOT.jar

test:
  stage: test
  script: mvn test
  image: maven:3.5.0-jdk-8