language: java

jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2/

install: mvn install -DskipTests=true

unittest: mvn test

script:
  - mvn compile

jobs:
  include:
    - stage: "compile"
      script: mvn compile
    - stage: "test"
      script: mvn test
    - stage: "package"
      script: mvn package
